### ISSUE TITLE
contact

### ISSUE THREAD

**Issue by bahoe** [chamaoskurumi/gentri#1]
Hallo,

in der Beschreibung schreibst du, dass du deine Originaldaten zur Verfügung stellen kannst, um dein R-Skript zu testen zu können, leider finde ich keine Möglichkeit dich direkt zu kontaktieren. 
Ich schreibe zur Zeit meine Masterarbeit in einem ähnlichen Bereich und möchte das Gentri-Modell auf einen Dresdner Stadtteil anwenden. Um dein Vorgehen nachvollziehen zu können würde es mir helfen deine Ergebnisse mit den Originaldaten reproduzieren zu können.

Über eine direkte Kontaktmöglichkeit würde ich mich freuen.

Beste Grüße,
Samuel

**Comment by chamaoskurumi** [comment]
hi Samuel,
schick mir mal deine Email Adresse, dann können wir uns absprechen und ich dir die Daten senden.

**Comment by bahoe** [comment]
Hi,
per Mail kam meine Antwort wahrscheinlich nicht an, deshalb findest du hier meine Adresse: https://paste.systemli.org/?924e53921748530f#+jB7rkwPZ58KD/aqPnH+rBJf4r42jaHczkJArMi6GMU=

Viele Grüße,
Samuel
